"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { ArrowLeft, CheckCircle2, Eye, EyeOff, Loader2, LockKeyhole, Mail, Phone, UserRound } from "lucide-react";
import { useAccount } from "@/components/account/account-provider";

export function LoginCard() {
  const { signIn, databaseReady } = useAccount(); const router = useRouter();
  const [show,setShow]=useState(false); const[loading,setLoading]=useState(false); const[error,setError]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setLoading(true);setError("");const result=await signIn(String(f.get("email")||""),String(f.get("password")||""));setLoading(false);if(result.error){setError(result.error);return;}router.push("/account");router.refresh();}
  return <AuthShell eyebrow="WELCOME BACK" title="أهلاً برجعتك" text="ادخلي لحسابك لمتابعة طلباتك، حالة الشحن وبيانات التوصيل."><form onSubmit={submit} className="space-y-4"><Field icon={Mail} label="البريد الإلكتروني"><input name="email" type="email" required defaultValue={!databaseReady?"demo@novamoda.jo":""} className="modern-input" placeholder="name@example.com"/></Field><Field icon={LockKeyhole} label="كلمة المرور"><div className="relative"><input name="password" type={show?"text":"password"} required defaultValue={!databaseReady?"123456":""} minLength={4} className="modern-input pl-12" placeholder="••••••••"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></Field>{!databaseReady&&<div className="preview-note"><CheckCircle2 size={15}/><span>وضع معاينة الحسابات مفعّل. البيانات أعلاه جاهزة لتجربة الواجهة.</span></div>}{error&&<div className="error-note">{error}</div>}<button disabled={loading} className="primary-auth-btn">{loading?<><Loader2 size={17} className="animate-spin"/>جاري الدخول...</>:<>دخول للحساب <ArrowLeft size={16}/></>}</button><p className="text-center text-xs text-[var(--muted)]">ما عندك حساب؟ <Link href="/register" className="font-extrabold text-[var(--brand-strong)]">إنشاء حساب جديد</Link></p></form></AuthShell>
}

export function RegisterCard(){const{register,databaseReady}=useAccount();const router=useRouter();const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const password=String(f.get("password")||"");const confirm=String(f.get("confirm")||"");if(password!==confirm){setError("كلمتا المرور غير متطابقتين.");return;}setLoading(true);setError("");const result=await register({fullName:String(f.get("fullName")||""),email:String(f.get("email")||""),phone:String(f.get("phone")||""),password,marketingConsent:f.get("marketingConsent")==="on"});setLoading(false);if(result.error){setError(result.error);return;}setMessage(result.message||"تم إنشاء الحساب.");if(!databaseReady)setTimeout(()=>router.push("/account"),550);}
return <AuthShell eyebrow="NOVA MEMBERS" title="حسابك، طلباتك، كل شيء بمكان واحد" text="أنشئي حساباً سريعاً لتتبعي حالة الطلب وتحفظي بياناتك للطلبات القادمة."><form onSubmit={submit} className="space-y-4"><Field icon={UserRound} label="الاسم الكامل"><input name="fullName" required className="modern-input" placeholder="الاسم الكامل"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field icon={Mail} label="البريد"><input name="email" type="email" required className="modern-input" placeholder="name@example.com"/></Field><Field icon={Phone} label="الهاتف"><input name="phone" inputMode="tel" className="modern-input" placeholder="07XXXXXXXX"/></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field icon={LockKeyhole} label="كلمة المرور"><input name="password" type="password" required minLength={6} className="modern-input" placeholder="6 خانات أو أكثر"/></Field><Field icon={LockKeyhole} label="تأكيد كلمة المرور"><input name="confirm" type="password" required minLength={6} className="modern-input" placeholder="أعيدي كتابتها"/></Field></div><label className="flex items-start gap-3 rounded-2xl border border-[var(--line)] bg-[var(--surface-soft)] p-4 text-[11px] font-bold leading-6 text-[var(--muted)]"><input name="marketingConsent" type="checkbox" className="mt-1"/><span><strong className="text-[var(--ink)]">أرغب باستلام جديد نوفا مودا والعروض.</strong><br/>اختياري، ويمكنك إلغاء الموافقة لاحقاً. بيانات الحساب تبقى محفوظة لتشغيل حسابك وطلباتك.</span></label>{error&&<div className="error-note">{error}</div>}{message&&<div className="success-note">{message}</div>}<button disabled={loading} className="primary-auth-btn">{loading?<><Loader2 size={17} className="animate-spin"/>جاري إنشاء الحساب...</>:<>إنشاء الحساب <ArrowLeft size={16}/></>}</button><p className="text-center text-xs text-[var(--muted)]">عندك حساب؟ <Link href="/login" className="font-extrabold text-[var(--brand-strong)]">تسجيل الدخول</Link></p></form></AuthShell>}

function Field({icon:Icon,label,children}:{icon:typeof Mail;label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 flex items-center gap-2 text-xs font-extrabold"><Icon size={14} className="text-[var(--brand-strong)]"/>{label}</span>{children}</label>}
function AuthShell({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children:React.ReactNode}){return <section className="container-shell py-10 sm:py-16"><div className="mx-auto grid max-w-[1040px] overflow-hidden rounded-[34px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_28px_90px_rgba(61,43,36,.10)] lg:grid-cols-[.9fr_1.1fr]"><div className="relative hidden min-h-[620px] overflow-hidden bg-[var(--ink)] p-9 text-[var(--paper)] lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 opacity-25 surface-grid"/><div className="absolute -left-24 top-10 h-72 w-72 rounded-full bg-[var(--brand)]/35 blur-3xl"/><div className="relative"><p className="text-[10px] font-extrabold tracking-[.24em] opacity-70">{eyebrow}</p><h2 className="mt-5 max-w-sm text-[38px] font-extrabold leading-[1.3]">{title}</h2><p className="mt-4 max-w-sm text-sm leading-7 opacity-70">{text}</p></div><div className="relative grid grid-cols-2 gap-3 text-xs"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><strong>تتبع الطلب</strong><p className="mt-1 text-[10px] leading-5 opacity-60">من التأكيد حتى التوصيل.</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><strong>تجربة أسرع</strong><p className="mt-1 text-[10px] leading-5 opacity-60">بياناتك محفوظة للطلب القادم.</p></div></div></div><div className="p-6 sm:p-9 lg:p-12"><div className="mb-8"><p className="text-[10px] font-extrabold tracking-[.2em] text-[var(--brand-strong)]">{eyebrow}</p><h1 className="mt-3 text-[30px] font-extrabold sm:text-[36px]">{title}</h1><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{text}</p></div>{children}</div></div></section>}
