"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Check, ChevronDown, CircleDashed, Clock3, Package, PackageCheck, Truck } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useAccount } from "@/components/account/account-provider";
import { createClient } from "@/lib/supabase/client";
import { formatPrice } from "@/lib/utils";

type OrderItem={id?:string;product_name:string;size:string;color?:string|null;qty:number;unit_price:number;line_total:number};
type CustomerOrder={id:string;order_number:string;status:string;total:number;created_at:string;city:string;address:string;order_items?:OrderItem[]};
const demoOrders:CustomerOrder[]=[
{id:"demo-1",order_number:"NM-260818-7F3A",status:"قيد التجهيز",total:54,created_at:"2026-08-18T18:25:00Z",city:"عمّان",address:"الشميساني - عمّان",order_items:[{product_name:"عباية سوداء مطرزة - لمسة روز قولد",size:"L",color:"أسود",qty:1,unit_price:52,line_total:52}]},
{id:"demo-2",order_number:"NM-260805-A91C",status:"تم التوصيل",total:47,created_at:"2026-08-05T12:10:00Z",city:"عمّان",address:"الشميساني - عمّان",order_items:[{product_name:"عباية كلاسيك فاخرة - بيج ملكي",size:"M",color:"بيج",qty:1,unit_price:45,line_total:45}]},
];
const steps=["جديد","قيد التجهيز","تم الشحن","تم التوصيل"];
export function OrdersView(){const{user,loading,databaseReady}=useAccount();const[orders,setOrders]=useState<CustomerOrder[]>([]);const[fetching,setFetching]=useState(true);useEffect(()=>{if(loading)return;if(!user){setFetching(false);return;}if(!databaseReady){try{const saved=JSON.parse(localStorage.getItem("nova-moda-demo-orders")||"[]") as CustomerOrder[];setOrders([...saved,...demoOrders]);}catch{setOrders(demoOrders)}setFetching(false);return;}const supabase=createClient();if(!supabase){setFetching(false);return;}supabase.from("orders").select("id,order_number,status,total,created_at,city,address,order_items(id,product_name,size,color,qty,unit_price,line_total)").order("created_at",{ascending:false}).then(({data})=>{setOrders((data||[]) as CustomerOrder[]);setFetching(false)});},[databaseReady,loading,user]);if(loading||fetching)return <div className="space-y-4">{[1,2].map(i=><div key={i} className="h-44 animate-pulse rounded-[28px] bg-[var(--surface-soft)]"/>)}</div>;if(!user)return <div className="account-panel text-center"><p className="font-extrabold">سجلي الدخول لمشاهدة طلباتك.</p><Link href="/login" className="mt-4 inline-block text-sm font-extrabold text-[var(--brand-strong)]">تسجيل الدخول</Link></div>;if(!orders.length)return <div className="account-panel text-center"><PackageCheck className="mx-auto text-[var(--brand-strong)]"/><h2 className="mt-4 text-xl font-extrabold">لسه ما عندك طلبات</h2><p className="mt-2 text-sm text-[var(--muted)]">أول طلب رح يظهر هون مع حالة التجهيز والشحن.</p><Link href="/shop" className="mt-5 inline-block rounded-full bg-[var(--ink)] px-5 py-2.5 text-xs font-extrabold text-[var(--paper)]">ابدئي التسوق</Link></div>;return <div className="space-y-4">{orders.map(order=><OrderCard key={order.id} order={order}/>)}</div>}
function OrderCard({order}:{order:CustomerOrder}){const[open,setOpen]=useState(false);const activeIndex=order.status==="ملغي"?-1:Math.max(0,steps.indexOf(order.status));return <motion.article layout className="overflow-hidden rounded-[28px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_15px_50px_rgba(61,43,36,.05)]"><button onClick={()=>setOpen(v=>!v)} className="w-full p-5 text-right sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-lg">{order.order_number}</strong><StatusBadge status={order.status}/></div><p className="mt-2 text-xs text-[var(--muted)]">{new Date(order.created_at).toLocaleDateString("ar-JO",{year:"numeric",month:"long",day:"numeric"})} • {formatPrice(Number(order.total))}</p></div><ChevronDown size={18} className={`mt-1 text-[var(--muted)] transition ${open?"rotate-180":""}`}/></div><div className="mt-6 grid grid-cols-4 gap-1"><TrackStep label="تم الطلب" icon={Check} active={activeIndex>=0} current={activeIndex===0}/><TrackStep label="قيد التجهيز" icon={Clock3} active={activeIndex>=1} current={activeIndex===1}/><TrackStep label="تم الشحن" icon={Truck} active={activeIndex>=2} current={activeIndex===2}/><TrackStep label="تم التوصيل" icon={PackageCheck} active={activeIndex>=3} current={activeIndex===3}/></div></button><AnimatePresence initial={false}>{open&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><div className="border-t border-[var(--line)] bg-[var(--surface-soft)] p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div><p className="text-xs font-extrabold">القطع</p><div className="mt-3 space-y-2">{order.order_items?.map((item,index)=><div key={item.id||index} className="flex items-center justify-between gap-4 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><div><strong className="text-sm">{item.product_name}</strong><p className="mt-1 text-[10px] text-[var(--muted)]">{item.size}{item.color?` • ${item.color}`:""} × {item.qty}</p></div><strong className="text-sm">{formatPrice(Number(item.line_total))}</strong></div>)}</div></div><div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><p className="text-xs font-extrabold">التوصيل إلى</p><p className="mt-2 text-xs leading-6 text-[var(--muted)]">{order.city}<br/>{order.address}</p></div></div></div></motion.div>}</AnimatePresence></motion.article>}
function TrackStep({label,icon:Icon,active,current}:{label:string;icon:typeof Package;active:boolean;current:boolean}){return <div className="relative text-center"><div className={`mx-auto grid h-9 w-9 place-items-center rounded-full border transition ${active?"border-[var(--brand)] bg-[var(--brand-soft)] text-[var(--brand-strong)]":"border-[var(--line)] bg-[var(--surface-soft)] text-[var(--muted)]"} ${current?"ring-4 ring-[var(--brand-soft)]":""}`}>{active?<Icon size={14}/>:<CircleDashed size={13}/>}</div><p className={`mt-2 text-[9px] font-extrabold sm:text-[10px] ${active?"text-[var(--ink)]":"text-[var(--muted)]"}`}>{label}</p></div>}
function StatusBadge({status}:{status:string}){const cls=status==="تم التوصيل"?"status-done":status==="تم الشحن"?"status-shipped":status==="قيد التجهيز"?"status-preparing":status==="ملغي"?"status-cancelled":"status-new";return <span className={`status-chip ${cls}`}>{status}</span>}
