"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Loader2, MapPin, Phone, Save, UserRound } from "lucide-react";
import { useAccount } from "@/components/account/account-provider";

const cities=["عمّان","إربد","الزرقاء","البلقاء","مادبا","جرش","عجلون","المفرق","الكرك","الطفيلة","معان","العقبة"];
export function ProfileForm(){const{user,loading,updateProfile}=useAccount();const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");useEffect(()=>{setMessage("");setError("")},[user]);if(loading)return <div className="h-96 animate-pulse rounded-[30px] bg-[var(--surface-soft)]"/>;if(!user)return <div className="account-panel text-center"><p>سجلي الدخول أولاً.</p><Link href="/login" className="mt-4 inline-block font-extrabold text-[var(--brand-strong)]">تسجيل الدخول</Link></div>;async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);setMessage("");setError("");const result=await updateProfile({fullName:String(f.get("fullName")||""),phone:String(f.get("phone")||""),city:String(f.get("city")||""),address:String(f.get("address")||"")});setSaving(false);if(result.error)setError(result.error);else setMessage("تم حفظ بياناتك بنجاح.");}
return <form onSubmit={submit} className="account-panel"><div className="grid gap-5 sm:grid-cols-2"><label><span className="profile-label"><UserRound size={14}/>الاسم الكامل</span><input name="fullName" defaultValue={user.fullName} required className="modern-input"/></label><label><span className="profile-label"><Phone size={14}/>رقم الهاتف</span><input name="phone" defaultValue={user.phone||""} inputMode="tel" className="modern-input"/></label><label><span className="profile-label"><MapPin size={14}/>المحافظة</span><select name="city" defaultValue={user.city||""} className="modern-input"><option value="">اختاري المحافظة</option>{cities.map(c=><option key={c}>{c}</option>)}</select></label><label className="sm:col-span-2"><span className="profile-label"><MapPin size={14}/>العنوان التفصيلي</span><input name="address" defaultValue={user.address||""} className="modern-input" placeholder="المنطقة، الشارع، أقرب معلم"/></label></div><div className="mt-5 rounded-2xl border border-[var(--line)] bg-[var(--surface-soft)] p-4"><p className="text-xs font-extrabold">البريد الإلكتروني</p><p className="mt-1 text-xs text-[var(--muted)]">{user.email}</p></div>{message&&<div className="success-note mt-4"><CheckCircle2 size={15}/>{message}</div>}{error&&<div className="error-note mt-4">{error}</div>}<button disabled={saving} className="primary-auth-btn mt-6 sm:w-fit sm:px-7">{saving?<><Loader2 size={16} className="animate-spin"/>جاري الحفظ...</>:<><Save size={16}/>حفظ التعديلات</>}</button></form>}
