"use client";
import Image from "next/image";
import Link from "next/link";
import { Search, X, ArrowUpLeft, Loader2 } from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useEffect, useRef, useState } from "react";
import type { Product } from "@/lib/types";
import { formatPrice } from "@/lib/utils";

export function SearchDialog({open,onClose}:{open:boolean;onClose:()=>void}){
  const reduce=useReducedMotion();const[q,setQ]=useState("");const[results,setResults]=useState<Product[]>([]);const[loading,setLoading]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(open){setTimeout(()=>inputRef.current?.focus(),80);document.body.style.overflow="hidden";}else document.body.style.overflow="";return()=>{document.body.style.overflow=""}},[open]);
  useEffect(()=>{if(!open||q.trim().length<2){setResults([]);return;}const c=new AbortController();const t=setTimeout(async()=>{setLoading(true);try{const r=await fetch(`/api/search?q=${encodeURIComponent(q.trim())}`,{signal:c.signal});const d=await r.json();setResults(d.products||[]);}catch{}finally{setLoading(false)}},220);return()=>{clearTimeout(t);c.abort();}},[q,open]);
  return <AnimatePresence>{open&&<motion.div initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[120] bg-black/35 p-3 backdrop-blur-sm sm:p-6" onMouseDown={e=>e.currentTarget===e.target&&onClose()}><motion.div initial={reduce?false:{opacity:0,y:-18,scale:.985}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-8}} transition={{duration:.25}} className="mx-auto mt-[7vh] max-h-[78vh] max-w-3xl overflow-hidden rounded-[28px] border border-[var(--line)] bg-[var(--surface)] shadow-2xl"><div className="flex items-center gap-3 border-b border-[var(--line)] p-4 sm:p-5"><Search size={20} className="text-[var(--muted)]"/><input ref={inputRef} value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحثي عن عباية، براند أو موديل..." className="min-w-0 flex-1 bg-transparent text-sm font-bold outline-none placeholder:text-[var(--muted)] sm:text-base"/><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full bg-[var(--surface-soft)]"><X size={17}/></button></div><div className="max-h-[62vh] overflow-auto p-3 sm:p-4">{loading&&<div className="grid place-items-center py-12 text-[var(--muted)]"><Loader2 className="animate-spin"/></div>}{!loading&&q.trim().length<2&&<div className="py-12 text-center"><p className="font-extrabold">اكتبي كلمتين أو أكثر</p><p className="mt-2 text-xs text-[var(--muted)]">مثال: عباية سوداء، Nova Daily، كريب</p></div>}{!loading&&q.trim().length>=2&&!results.length&&<div className="py-12 text-center"><p className="font-extrabold">ما لقينا نتيجة مطابقة</p><Link href={`/search?q=${encodeURIComponent(q)}`} onClick={onClose} className="mt-4 inline-flex rounded-full border border-[var(--line)] px-4 py-2 text-xs font-extrabold">عرض صفحة البحث</Link></div>}{!loading&&results.length>0&&<div className="grid gap-2">{results.slice(0,7).map(p=><Link key={p.id} href={`/product/${p.slug}`} onClick={onClose} className="group flex items-center gap-3 rounded-2xl p-2.5 transition hover:bg-[var(--surface-soft)]"><div className="relative h-16 w-14 shrink-0 overflow-hidden rounded-xl bg-[var(--surface-soft)]"><Image src={p.images[0]||"/products/abaya-classic-beige.svg"} alt={p.name} fill className="object-cover" sizes="56px"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{p.name}</p><p className="mt-1 text-[11px] text-[var(--muted)]">{p.brand?.name||p.category?.name||"Nova Moda"} • {formatPrice(p.price)}</p></div><ArrowUpLeft size={16} className="text-[var(--muted)] transition group-hover:-translate-x-1 group-hover:-translate-y-1"/></Link>)}</div>}</div></motion.div></motion.div>}</AnimatePresence>
}
