"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Plus, Save, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { AboutContent, Faq, Testimonial } from "@/lib/types";

type Tab = "about" | "faq" | "reviews";

export function ContentManager({ about, faqs, testimonials }: { about: AboutContent; faqs: Faq[]; testimonials: Testimonial[] }) {
  const router=useRouter(); const [tab,setTab]=useState<Tab>("about"); const [aboutDraft,setAboutDraft]=useState(about); const [whyText,setWhyText]=useState(about.why_points.join("\n")); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  async function saveAbout(){const supabase=createClient();if(!supabase)return;setSaving(true);setMessage("");const content={...aboutDraft,why_points:whyText.split("\n").map(x=>x.trim()).filter(Boolean)};const {error}=await supabase.from("page_content").upsert({key:"about",content,updated_at:new Date().toISOString()},{onConflict:"key"});setSaving(false);if(error)setMessage(error.message);else{setMessage("تم حفظ صفحة من نحن");router.refresh();}}
  return <div className="space-y-5"><section className="rounded-2xl border border-[#E6D8CE] bg-white p-3"><div className="flex gap-2 overflow-x-auto">{([{id:"about",label:"من نحن"},{id:"faq",label:"الأسئلة الشائعة"},{id:"reviews",label:"آراء العملاء"}] as {id:Tab;label:string}[]).map(item=><button key={item.id} onClick={()=>{setTab(item.id);setMessage("")}} className={`shrink-0 rounded-full px-5 py-2.5 text-xs font-extrabold ${tab===item.id?"bg-[#3D2B24] text-white":"bg-[#FDF6F0]"}`}>{item.label}</button>)}</div></section>
    {tab==="about"&&<section className="rounded-2xl border border-[#E6D8CE] bg-white p-5 sm:p-6"><p className="text-xs font-extrabold tracking-[.14em] text-[#A27E6C]">ABOUT PAGE</p><h1 className="mt-1 text-2xl font-extrabold">تحرير صفحة من نحن</h1><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="النص الصغير"><input className="admin-input mt-2" value={aboutDraft.eyebrow} onChange={e=>setAboutDraft({...aboutDraft,eyebrow:e.target.value})}/></Field><Field label="العنوان"><input className="admin-input mt-2" value={aboutDraft.title} onChange={e=>setAboutDraft({...aboutDraft,title:e.target.value})}/></Field><Field label="المقدمة" className="md:col-span-2"><textarea rows={5} className="admin-input mt-2 resize-none" value={aboutDraft.intro} onChange={e=>setAboutDraft({...aboutDraft,intro:e.target.value})}/></Field><Field label="عنوان مراحل العمل"><input className="admin-input mt-2" value={aboutDraft.process_title} onChange={e=>setAboutDraft({...aboutDraft,process_title:e.target.value})}/></Field><Field label="وصف مراحل العمل"><input className="admin-input mt-2" value={aboutDraft.process_intro} onChange={e=>setAboutDraft({...aboutDraft,process_intro:e.target.value})}/></Field><Field label="عنوان لماذا نوفا مودا"><input className="admin-input mt-2" value={aboutDraft.why_title} onChange={e=>setAboutDraft({...aboutDraft,why_title:e.target.value})}/></Field><Field label="وصف القسم"><input className="admin-input mt-2" value={aboutDraft.why_intro} onChange={e=>setAboutDraft({...aboutDraft,why_intro:e.target.value})}/></Field><Field label="النقاط - كل نقطة بسطر" className="md:col-span-2"><textarea rows={7} className="admin-input mt-2 resize-none" value={whyText} onChange={e=>setWhyText(e.target.value)}/></Field></div><button onClick={saveAbout} disabled={saving} className="mt-5 flex min-h-11 items-center gap-2 rounded-full bg-[#3D2B24] px-6 text-xs font-extrabold text-white">{saving?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>}حفظ المحتوى</button></section>}
    {tab==="faq"&&<FaqEditor faqs={faqs} onChanged={()=>router.refresh()}/>} {tab==="reviews"&&<TestimonialsEditor testimonials={testimonials} onChanged={()=>router.refresh()}/>} {message&&<div className="rounded-xl bg-[#FDF6F0] p-3 text-xs font-bold">{message}</div>}
  </div>;
}

function FaqEditor({faqs,onChanged}:{faqs:Faq[];onChanged:()=>void}){const [question,setQuestion]=useState("");const [answer,setAnswer]=useState("");const [error,setError]=useState("");async function add(){if(!question.trim()||!answer.trim())return;const supabase=createClient();if(!supabase)return;const {error}=await supabase.from("faqs").insert({question:question.trim(),answer:answer.trim(),active:true,sort_order:faqs.length+1});if(error)setError(error.message);else{setQuestion("");setAnswer("");onChanged();}}async function update(item:Faq,patch:Partial<Faq>){const supabase=createClient();if(!supabase)return;const {error}=await supabase.from("faqs").update(patch).eq("id",item.id);if(error)setError(error.message);else onChanged();}async function remove(id:string){if(!confirm("حذف السؤال؟"))return;const supabase=createClient();if(!supabase)return;const {error}=await supabase.from("faqs").delete().eq("id",id);if(error)setError(error.message);else onChanged();}return <section className="rounded-2xl border border-[#E6D8CE] bg-white p-5 sm:p-6"><h1 className="text-2xl font-extrabold">الأسئلة الشائعة</h1><div className="mt-5 rounded-2xl bg-[#FDF6F0] p-4"><input value={question} onChange={e=>setQuestion(e.target.value)} className="admin-input" placeholder="السؤال"/><textarea value={answer} onChange={e=>setAnswer(e.target.value)} rows={3} className="admin-input mt-3 resize-none" placeholder="الجواب"/><button onClick={add} className="mt-3 flex items-center gap-2 rounded-full bg-[#3D2B24] px-5 py-2.5 text-xs font-extrabold text-white"><Plus size={13}/>إضافة سؤال</button></div>{error&&<p className="mt-3 text-xs text-red-600">{error}</p>}<div className="mt-4 space-y-3">{faqs.map(item=><div key={item.id} className="rounded-2xl border border-[#EEE1D7] p-4"><input defaultValue={item.question} onBlur={e=>e.target.value!==item.question&&update(item,{question:e.target.value})} className="admin-input font-bold"/><textarea defaultValue={item.answer} onBlur={e=>e.target.value!==item.answer&&update(item,{answer:e.target.value})} rows={3} className="admin-input mt-2 resize-none"/><div className="mt-2 flex items-center gap-3"><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={item.active} onChange={e=>update(item,{active:e.target.checked})}/>مفعل</label><button onClick={()=>remove(item.id)} className="mr-auto grid h-8 w-8 place-items-center rounded-full bg-red-50 text-red-600"><Trash2 size={13}/></button></div></div>)}</div></section>}

function TestimonialsEditor({testimonials,onChanged}:{testimonials:Testimonial[];onChanged:()=>void}){const [name,setName]=useState("");const [text,setText]=useState("");const [error,setError]=useState("");async function add(){if(!name.trim()||!text.trim())return;const supabase=createClient();if(!supabase)return;const {error}=await supabase.from("testimonials").insert({customer_name:name.trim(),text:text.trim(),rating:5,active:true,sort_order:testimonials.length+1});if(error)setError(error.message);else{setName("");setText("");onChanged();}}async function update(item:Testimonial,patch:Partial<Testimonial>){const supabase=createClient();if(!supabase)return;const {error}=await supabase.from("testimonials").update(patch).eq("id",item.id);if(error)setError(error.message);else onChanged();}async function remove(id:string){if(!confirm("حذف الرأي؟"))return;const supabase=createClient();if(!supabase)return;const {error}=await supabase.from("testimonials").delete().eq("id",id);if(error)setError(error.message);else onChanged();}return <section className="rounded-2xl border border-[#E6D8CE] bg-white p-5 sm:p-6"><h1 className="text-2xl font-extrabold">آراء العملاء</h1><div className="mt-5 rounded-2xl bg-[#FDF6F0] p-4"><input value={name} onChange={e=>setName(e.target.value)} className="admin-input" placeholder="اسم العميلة"/><textarea value={text} onChange={e=>setText(e.target.value)} rows={3} className="admin-input mt-3 resize-none" placeholder="الرأي"/><button onClick={add} className="mt-3 flex items-center gap-2 rounded-full bg-[#3D2B24] px-5 py-2.5 text-xs font-extrabold text-white"><Plus size={13}/>إضافة رأي</button></div>{error&&<p className="mt-3 text-xs text-red-600">{error}</p>}<div className="mt-4 grid gap-3 md:grid-cols-2">{testimonials.map(item=><div key={item.id} className="rounded-2xl border border-[#EEE1D7] p-4"><input defaultValue={item.customer_name} onBlur={e=>e.target.value!==item.customer_name&&update(item,{customer_name:e.target.value})} className="admin-input font-bold"/><textarea defaultValue={item.text} onBlur={e=>e.target.value!==item.text&&update(item,{text:e.target.value})} rows={4} className="admin-input mt-2 resize-none"/><div className="mt-2 flex items-center gap-3"><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={item.active} onChange={e=>update(item,{active:e.target.checked})}/>مفعل</label><select value={item.rating} onChange={e=>update(item,{rating:Number(e.target.value)})} className="rounded-lg border border-[#E6D8CE] bg-white px-2 py-1 text-xs">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} نجوم</option>)}</select><button onClick={()=>remove(item.id)} className="mr-auto grid h-8 w-8 place-items-center rounded-full bg-red-50 text-red-600"><Trash2 size={13}/></button></div></div>)}</div></section>}

function Field({label,className="",children}:{label:string;className?:string;children:React.ReactNode}){return <label className={`block text-xs font-bold ${className}`}>{label}{children}</label>}
