import type { Metadata } from "next";
import Image from "next/image";
import { Check, Heart, Ruler, Scissors, Sparkles } from "lucide-react";
import { AnimatedSection } from "@/components/ui/animated-section";
import { getAboutContent } from "@/lib/data";

export const metadata: Metadata = { title: "من نحن", description: "تعرفي على قصة نوفا مودا وطريقتنا في اختيار الأقمشة والتفصيل وصناعة العبايات." };

export default async function AboutPage() {
  const content = await getAboutContent();
  return <><section className="border-b border-[#F0E6DC] bg-[#FDF6F0] py-14 sm:py-20"><div className="container-shell grid items-center gap-10 lg:grid-cols-2"><AnimatedSection><p className="text-xs font-extrabold tracking-[.14em] text-[#A27E6C]">{content.eyebrow}</p><h1 className="mt-3 text-[38px] font-extrabold leading-[1.35] sm:text-[52px]">{content.title}</h1><p className="mt-5 text-[15px] leading-9 text-[#67534B]">{content.intro}</p></AnimatedSection><AnimatedSection delay={.08}><div className="relative mx-auto aspect-[4/3] max-w-[560px] overflow-hidden rounded-[34px] border border-[#E8D7CB] bg-[var(--logo-plate)] surface-grid"><div className="absolute inset-0 grid place-items-center"><Image src="/brand/nova-moda-logo-clean.png" alt="نوفا مودا" width={550} height={636} className="h-[78%] w-auto object-contain"/></div></div></AnimatedSection></div></section>
  <section className="py-16 sm:py-20"><div className="container-shell"><AnimatedSection className="mx-auto mb-10 max-w-2xl text-center"><p className="text-xs font-extrabold tracking-[.14em] text-[#A27E6C]">HOW WE WORK</p><h2 className="mt-2 text-[32px] font-extrabold sm:text-[40px]">{content.process_title}</h2><p className="mt-3 text-sm leading-7 text-[#7A655C]">{content.process_intro}</p></AnimatedSection><div className="grid gap-4 md:grid-cols-4">{[{icon:Sparkles,title:"التصميم",text:"نبدأ بقصات تجمع الراحة والحداثة وتناسب الاستخدام الحقيقي."},{icon:Scissors,title:"اختيار القماش",text:"نختار خامات مريحة، غير شفافة، وتتحمل الاستخدام والعناية."},{icon:Ruler,title:"القص والتفصيل",text:"قياسات واضحة وخياطة مرتبة وتشطيب نهائي نظيف."},{icon:Heart,title:"الفحص والتغليف",text:"كل قطعة تمر بفحص نهائي قبل تجهيزها للعميلة."}].map(({icon:Icon,title,text},i)=><AnimatedSection key={title} delay={i*.05} className="rounded-[24px] border border-[#E9DBD0] bg-white p-6"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#F5E8DF]"><Icon size={18}/></div><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-7 text-[#7A655C]">{text}</p></AnimatedSection>)}</div></div></section>
  <section className="bg-[#3D2B24] py-16 text-white sm:py-20"><div className="container-shell grid gap-9 lg:grid-cols-[.85fr_1.15fr]"><AnimatedSection><p className="text-xs font-bold tracking-[.14em] text-[#DDBCA6]">WHY NOVA MODA</p><h2 className="mt-3 text-[34px] font-extrabold leading-[1.4]">{content.why_title}</h2><p className="mt-4 text-sm leading-7 text-white/60">{content.why_intro}</p></AnimatedSection><div className="grid gap-3 sm:grid-cols-2">{content.why_points.map((item,i)=><AnimatedSection key={item} delay={i*.04} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm font-bold"><span className="grid h-7 w-7 place-items-center rounded-full bg-white/10"><Check size={14}/></span>{item}</AnimatedSection>)}</div></div></section></>;
}
